server:
    port: 8080
spring:
    profiles:
        active: default
city:
  latitude: 51.507351
  longitude: -0.118092

logging:
  level:
    root: INFO
 
app:
   name: UserCityServiceClient   
   
bpdts:
  test:
    app: bpdts-test-app.herokuapp.com
 
